spring.application.name=intranet

# =====================================
# BANCO
# =====================================

spring.datasource.url=jdbc:h2:mem:officefrutas;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =====================================
# KAIROS
# =====================================

kairos.base-url=https://www.dimepkairos.com.br
kairos.identifier=${KAIROS_IDENTIFIER:}
kairos.api-key=${KAIROS_API_KEY:}


# =====================================
# JWT
# =====================================

jwt.secret=${JWT_SECRET:}
jwt.issuer=intranet-officefrutas
jwt.expiration-seconds=3600